name: Better_Spawners
main: me.silentprogram.betterspawnerspremium.BetterSpawners
version: 1.0.0
api-version: 1.16
description: Premium spawners plugin

commands:
  spawners:
    description: Opens the spawner gui